apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113
  selector:
    app: nginx-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
  - port: http
    interval: 30s

